### ISSUE TITLE
Use PSR-4 autoloading and remove directory depth

### ISSUE THREAD

**Issue by 7ochem** [zicht/key-value-bundle#33]
Change from PSR-0 to PSR-4 autoloading in composer.json and remove the unneccesary directory depth in src/ and tests/

Check the code for any path related issues (locating files/folders with `__DIR__ . '/../../../'` or something)

**Comment by erik-zicht** [comment]
Done in https://github.com/zicht/key-value-bundle/blob/release/4.x/composer.json
